### ISSUE TITLE
Will this plugin work cakephp 1.3

### ISSUE THREAD

**Issue by Nick5679** [shama/cakebox#1]
hi,

I would like use this plugin in an existing project. I have not migrated to cakephp 2.0 yet. I was wondering if this plugin will be compatible with cakephp 1.3. 

I appreciate all your help.

**Comment by shama** [comment]
It will not... only CakePHP 2+. Although it is pretty easy to upgrade to 2 especially with the upgrade shell (http://book.cakephp.org/2.0/en/console-and-shells/upgrade-shell.html)... and likely easier than it would be to downgrade this plugin for 1.3. You won't regret migrating to 2, its great! :)

**Comment by Nick5679** [comment]
Thanks. I am looking forward to working with cakephp 2+.
